@startuml
scale 1920*1080
!include ../Archimate.puml

title Value Stream Map Aggregation

Strategy_ValueStream(design, "**Design**\n12-24 hours work time\n6-9 days wall time") 
Strategy_ValueStream(visualize_features, "**Visualize features**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(draft_mockups, "**Draft mockups**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(confirm_plans, "**Confirm plans with customers**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(design, visualize_features)
Rel_Aggregation_Down(design, draft_mockups)
Rel_Aggregation_Down(design, confirm_plans)
Rel_Flow_Right(visualize_features, draft_mockups)
Rel_Flow_Right(draft_mockups, confirm_plans)

Strategy_ValueStream(develop, "**Develop**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(code_front_end, "**Code front-end dashboards**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(program_back_end, "**Program back-end services**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(update_documentation, "**Update documentation**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(develop, code_front_end)
Rel_Aggregation_Down(develop, program_back_end)
Rel_Aggregation_Down(develop, update_documentation)
Rel_Flow_Right(code_front_end, program_back_end)
Rel_Flow_Right(program_back_end,update_documentation)

Strategy_ValueStream(deploy, "**Deploy**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(push_topic, "**Push topic branch**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(review_code, "**Review code and test it**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(release_build, "**Release build into production**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(deploy, push_topic)
Rel_Aggregation_Down(deploy, review_code)
Rel_Aggregation_Down(deploy, release_build)
Rel_Flow_Right(push_topic, review_code)
Rel_Flow_Right(review_code, release_build)

Strategy_ValueStream(deliver, "**Deliver**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(sign_acceptance, "**Sign acceptance**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(refresh_nps, "**Refresh Net Promoter Score**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(send_invoice, "**Send invoice and get paid **\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(deliver, sign_acceptance)
Rel_Aggregation_Down(deliver, refresh_nps)
Rel_Aggregation_Down(deliver, send_invoice)
Rel_Flow_Right(sign_acceptance, refresh_nps)
Rel_Flow_Right(refresh_nps, send_invoice)

Rel_Flow_Right(design, develop)
Rel_Flow_Right(develop, deploy)
Rel_Flow_Right(deploy, deliver)

' Hidden: from higher-level into lower-level middle element
design -[hidden]d-> draft_mockups
develop -[hidden]d-> program_back_end
deploy -[hidden]d-> review_code
deliver -[hidden]d-> refresh_nps

' If you prefer to see just the value stream steps,
' then you can comment out the following lines.

Motivation_Stakeholder(customer_team, "**Customer Team**\n\n--\nDriver: Solving their pain point\n--\nAssessment: GUI is confusing\n--\nGoal: Navigation link to new item")
Motivation_Stakeholder(account_executive, "**Account Executive**\n\n--\nDriver: sales-led satisfaction\n--\nAssessment: Priority 1 papercut\n--\nGoal: Net Promoter Score 25+")
Motivation_Stakeholder(product_manager, "**Product Manager**\n\n--\nDriver: product-led growth\n--\nAssessment: Can help all accounts\n--\nGoal: Kanban zero papercuts")
Motivation_Stakeholder(work_squad, "**Work Squad**\n\n--\nDriver: feature-led delivery\n--\nAssessment: Size is small\n--\nGoal: Deliver by end of week 40")

Rel_Flow_Left(customer_team, account_executive)
Rel_Flow_Left(account_executive, product_manager)
Rel_Flow_Left(product_manager, work_squad)

Rel_Flow_Down(work_squad, design)
Rel_Flow_Up(deliver, customer_team)

' Hidden: from stakeholder to value stream step
work_squad -[hidden]d-> design
product_manager -[hidden]d-> develop
account_executive -[hidden]d-> deploy
customer_team -[hidden]d-> deliver

@enduml