@startuml
scale 1920*1080
!include ../../../Archimate.puml

title Value Stream Map Aggregation

Strategy_ValueStream(design, "**Design**\n12-24 hours work time\n6-9 days wall time") 
Strategy_ValueStream(visualize_features, "**Visualize features**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(draft_mockups, "**Draft mockups**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(confirm_plans, "**Confirm plans with customers**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(design, visualize_features)
Rel_Aggregation_Down(design, draft_mockups)
Rel_Aggregation_Down(design, confirm_plans)
Rel_Flow_Right(visualize_features, draft_mockups, "Wait time #1:\n1-2 hours")
Rel_Flow_Right(draft_mockups, confirm_plans, "Wait time #2:\n 1-2 hours")

Strategy_ValueStream(develop, "**Develop**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(code_front_end, "**Code front-end dashboards**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(program_back_end, "**Program back-end services**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(update_documentation, "**Update documentation**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(develop, code_front_end)
Rel_Aggregation_Down(develop, program_back_end)
Rel_Aggregation_Down(develop, update_documentation)
Rel_Flow_Right(code_front_end, program_back_end, "Wait time #4:\n 1-2 hours")
Rel_Flow_Right(program_back_end,update_documentation, "Wait time #5:\n 1-2 hours")

Strategy_ValueStream(deploy, "**Deploy**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(push_topic, "**Push topic branch**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(review_code, "**Review code and test it**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(release_build, "**Release build into production**\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(deploy, push_topic)
Rel_Aggregation_Down(deploy, review_code)
Rel_Aggregation_Down(deploy, release_build)
Rel_Flow_Right(push_topic, review_code, "Wait time #7:\n 1-2 hours")
Rel_Flow_Right(review_code, release_build, "Wait time #8:\n 1-2 hours")

Strategy_ValueStream(deliver, "**Deliver**\n12-24 hours work time\n6-9 days wall time")
Strategy_ValueStream(sign_acceptance, "**Sign acceptance**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(refresh_nps, "**Refresh Net Promoter Score**\n4-8 hours work time\n2-3 days wall time")
Strategy_ValueStream(send_invoice, "**Send invoice and get paid **\n4-8 hours work time\n2-3 days wall time")
Rel_Aggregation_Down(deliver, sign_acceptance)
Rel_Aggregation_Down(deliver, refresh_nps)
Rel_Aggregation_Down(deliver, send_invoice)
Rel_Flow_Right(sign_acceptance, refresh_nps, "Wait time #10:\n 1-2 hours")
Rel_Flow_Right(refresh_nps, send_invoice, "Wait time #11:\n 1-2 hours")

' Upper-layer right arrows
Rel_Flow_Right(design, develop)
Rel_Flow_Right(develop, deploy)
Rel_Flow_Right(deploy, deliver)

' Lower-layer right arrows
Rel_Flow_Right(confirm_plans, code_front_end, "Wait time #3:\n 1-2 hours")
Rel_Flow_Right(update_documentation, push_topic, "Wait time #6:\n 1-2 hours")
Rel_Flow_Right(release_build, sign_acceptance, "Wait time #9:\n 1-2 hours")


' Hidden: from higher-level into lower-level middle element
design -[hidden]d-> draft_mockups
develop -[hidden]d-> program_back_end
deploy -[hidden]d-> review_code
deliver -[hidden]d-> refresh_nps

' Stakeholder elements
'
' If you prefer to see just the value stream steps,
' then you can comment out the following lines.

Motivation_Stakeholder(customer_team, "**Customer Team**\n\n--\nDriver: Solving pain point\n--\nAssessment: GUI is confusing\n--\nGoal: Navigation link to new item")
Motivation_Stakeholder(account_manager, "**Account Manager**\n\n--\nDriver: Sales-led satisfaction\n--\nAssessment: Priority 1 papercut\n--\nGoal: Net Promoter Score 25+")
Motivation_Stakeholder(product_manager, "**Product Manager**\n\n--\nDriver: Product-led growth\n--\nAssessment: Magnitude 2 feature\n--\nGoal: Kanban zero papercuts")
Motivation_Stakeholder(work_squad, "**Work Squad**\n\n--\nDriver: Feature-led delivery\n--\nAssessment: Size is small\n--\nGoal: Deliver by end of week 40")

Rel_Flow_Left(customer_team, account_manager)
Rel_Flow_Left(account_manager, product_manager)
Rel_Flow_Left(product_manager, work_squad)

Rel_Flow_Down(work_squad, design)
Rel_Flow_Up(deliver, customer_team)

' Hidden: from stakeholder to value stream step
work_squad -[hidden]d-> design
product_manager -[hidden]d-> develop
account_manager -[hidden]d-> deploy
customer_team -[hidden]d-> deliver

' Deliverable elements
'
' If you prefer to see just the value stream steps,
' then you can comment out the following lines.

Implementation_Deliverable(visualizations, "**Visualizations**\n\n--\nSign off")
Rel_Realization_Down(visualize_features, visualizations)

Implementation_Deliverable(mockups, "**Mockups**\n\n--\nSign off")
Rel_Realization_Down(draft_mockups, mockups)

Implementation_Deliverable(plans, "**Plans**\n\n--\nSign off")
Rel_Realization_Down(confirm_plans, plans)

Implementation_Deliverable(front_end, "**Front-end dashboards**\n\n--\nPublished Screenshots")
Rel_Realization_Down(code_front_end, front_end)

Implementation_Deliverable(back_end, "**Back-end services**\n\n--\nPublished OpenAPI spec")
Rel_Realization_Down(program_back_end, back_end)

Implementation_Deliverable(documentation, "**Documentation**\n\n--\nPublished HTML pages")
Rel_Realization_Down(update_documentation, documentation) 

Implementation_Deliverable(topic_branch, "**Topic branch**\n\n--\nMerge is requested")
Rel_Realization_Down(push_topic, topic_branch)

Implementation_Deliverable(code_approval, "**Code approval**\n\n--\nMerge is integrated")
Rel_Realization_Down(review_code, code_approval)

Implementation_Deliverable(live_in_production, "**Live in production**\n\n--\nMerge is deployed")
Rel_Realization_Down(release_build, live_in_production)

Implementation_Deliverable(customer_acceptance, "**Customer acceptance**\n\n--\nDelivery sign off")
Rel_Realization_Down(sign_acceptance, customer_acceptance)

Implementation_Deliverable(nps, "**Net Promoter Score**\n\n--\nDelta in metrics")
Rel_Realization_Down(refresh_nps, nps)

Implementation_Deliverable(payment, "**Payment**\n\n--\nMoney in bank")
Rel_Realization_Down(send_invoice, payment)

@enduml